name: Display Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build-And-Upload:
    runs-on: macos-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: npm
      - name: Cache Setup
        uses: actions/cache/restore@v4
        with:
          path: |
            /Users/runner/Library/Caches/pip
            ~/.oci-cli-installed
          key: ${{ runner.os }}-display-build
      - name: Install
        run: npm ci --include=dev --verbose --force
      - name: Build
        if: ${{ success() }}
        run: npm run build
      - name: Delete Contents
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          silent: false
          command: os object bulk-delete --namespace-name ${{ vars.OCI_OBJECT_STORAGE_NAMESPACE }} --bucket-name ${{ vars.ACCOUNTS_BUCKET_NAME }} --force
      - name: Upload Contents
        run: ./upload-display.sh ${{ vars.OCI_OBJECT_STORAGE_NAMESPACE }} ${{ vars.ACCOUNTS_BUCKET_NAME }}